name: Build and Export JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package

      - name: Export JAR file
        run: cp target/PixelCore.jar build/PixelCore.jar
