name: Build and Export JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Eclipse
        run: |
          mkdir -p build
          cp -R src build/
          cp -R libs build/
          javac -d build -sourcepath src -classpath libs/* src/io/github/birajrai/*.java

      - name: Export JAR file
        run: jar cvf build/PixelCore.jar -C build .
